# config for TEST env

spring:
    datasource:
        url: "jdbc:postgresql://${ADMIN_API_DB_SERVICE:localhost}:5432/example_app_test"
        username: "test_app"
        password: "test_password"

logging.config: classpath:log4j2-dev.xml
